### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Dourmi** [Alphalaneous/Minecraftify#5]
![Screenshot_2024-12-27-20-16-19-79_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/user-attachments/assets/bcd06679-ef07-47e0-a167-57ed64813a31)

**Comment by Alphalaneous** [comment]
This just means you have an incompatible mod installed. Icon ninja, better menu, overcharged main menu, daily transfer, and deltarune text boxes are incompatible with Minecraftify.

**Comment by Dourmi** [comment]
Thank you!
